name: Build-and-publish-docker-images-workflow

on:
  push:
    branches:
      - main
      - master
      - '*/Fix-*-docker*'

  release:
    types: [published]

jobs:
  Build-and-publish-docker-images:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, 'The workflow build-and-publish-docker-images was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master
        
      - name: Build and publish AasxServerBlazor
        uses: docker/build-push-action@v1
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-blazor-for-demo
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerBlazor

      - name: Build and publish AasxServerBlazor-arm32
        uses: docker/build-push-action@v1
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-blazor-for-demo-arm32
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerBlazor-arm32

      - name: Build and publish AasxServerBlazor-arm64
        uses: docker/build-push-action@v1
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-blazor-for-demo-arm64
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerBlazor-arm64

      - name: Build and publish AasxServerCore
        uses: docker/build-push-action@v1
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-core-for-demo
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerCore

      - name: Build and publish AasxServerCore-arm32
        uses: docker/build-push-action@v1
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-core-for-demo-arm32
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerCore-arm32

      - name: Build and publish AasxServerCore-arm64
        uses: docker/build-push-action@v1
        with:
          username: adminshellio
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adminshellio/aasx-server-core-for-demo-arm64
          tag_with_ref: true
          dockerfile: src/docker/Dockerfile-AasxServerCore-arm64
