name: Check-style-workflow

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - master

jobs:
  Check-style:
    runs-on: windows-latest
    if: contains(github.event.pull_request.body, 'The workflow check-style was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Install dotnet tools
        working-directory: src
        run: dotnet tool restore
        if: always()

      - name: Check format
        working-directory: src
        run: powershell .\CheckFormat.ps1
        if: always()
