name: Check-release-workflow

on:
  pull_request:
    branches:
      - master
      - masterV3
    types: [opened, synchronize, reopened, edited]

  push:
    branches:
      - master
      - masterV3

jobs:
  Check-release:
    runs-on: windows-latest
    if: contains(github.event.pull_request.body, 'The workflow check-release was intentionally skipped.') == false
    steps:
      - uses: actions/checkout@master

      - name: Set timestamp
        id: setTimestamp
        run: |
          $timestamp = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH-mm-ssZ")
          if ($timestamp.Contains("'"))
          {
              throw "Unexpected timestamp containing a single quote: $timestamp"
          }
          if ($timestamp.Contains('"'))
          {
              throw "Unexpected timestamp containing a double quote: $timestamp"
          }
          if ($timestamp.Contains(':'))
          {
              throw "Unexpected timestamp containing a full colon: $timestamp"
          }

          Write-Output "::set-output name=timestamp::$timestamp"

      - name: Install .NET core 3.1
        if: ${{ !contains(github.ref, 'V3') }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Install .NET core 6.0
        if: ${{ contains(github.ref, 'V3') || contains(github.ref, 'V3') }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build for release
        working-directory: src
        run: powershell .\BuildForRelease.ps1

      - name: Check --help and Readme coincide
        working-directory: src
        run: powershell .\CheckHelpInReadme.ps1

      - name: Package
        working-directory: src
        run: powershell .\PackageRelease.ps1 -version LATEST.alpha

      - name: Upload AasxServerBlazor
        uses: actions/upload-artifact@v2
        with:
          name: AasxServerBlazor.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/AasxServerBlazor.zip

      - name: Upload AasxServerCore
        uses: actions/upload-artifact@v2
        with:
          name: AasxServerCore.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/AasxServerCore.zip

      - name: Upload AasxServerWindows
        uses: actions/upload-artifact@v2
        with:
          name: AasxServerWindows.LATEST.alpha.${{ steps.setTimestamp.outputs.timestamp }}
          path: artefacts/release/LATEST.alpha/AasxServerWindows.zip
