name: Build-and-package-release-workflow

on:
  push:
    branches:
      - main

jobs:
  Build-and-package-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Install .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - name: Build for the release
        working-directory: SOURCE/Server2/aasx-server/src
        run: powershell .\BuildForRelease.ps1

      - name: Package the release
        working-directory: SOURCE/Server2/aasx-server/src
        run: |
          Write-Host "Packaging for the Deploy version"
          powershell .\PackageRelease.ps1
      
      - name: upload file
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          username: ${{ secrets.FTP_USERNAME }}
          host: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          localDir: 'SOURCE/Server2/aasx-server/artefacts/release/AasxServerBlazor.zip'
          remoteDir: 'Server'

